<?php

/**
 * Implements hook_preprocess_HOOK().
 */

/**
 * Implements hook_preprocess().
 */
function random_theme_preprocess_page_title(&$data) {

  $usr = $data['user']->getAccountName();
  $pg = $data['title']['#markup'];

  $data['title']['#markup'] = Drupal\Core\Render\Markup::create(($pg . ', ' . $usr));
  $data['title']['#children'] = Drupal\Core\Render\Markup::create(($pg . ', ' . $usr));


}
